# Generated by Django 3.0.2 on 2020-02-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='employees',
        ),
    ]
